apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: seldon-mock-model
spec:
  annotations:
    seldon.io/executor: "true"
  name: mock-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: mock-model:latest
          imagePullPolicy: IfNotPresent
          name: my-mock-model
    graph:
      children: []
      endpoint:
        type: REST
      name: my-mock-model
      type: MODEL
    labels:
      version: v1
    name: my-mock-graph
    replicas: 1
