apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: combiner-experiments
spec:
  name: combiner-experiments
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: model-a
          image: combiner-test:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: MODEL_NAME
            value: ModelA

          - name: SELDON_LOG_LEVEL
            value: DEBUG

          - name: SELDON_DEBUG
            value: "true"

        - name: model-b
          image: combiner-test:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: MODEL_NAME
            value: ModelB

          - name: SELDON_LOG_LEVEL
            value: DEBUG

          - name: SELDON_DEBUG
            value: "true"

        - name: combiner
          image: combiner-test:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: MODEL_NAME
            value: Combiner

          - name: SELDON_LOG_LEVEL
            value: DEBUG

          - name: SELDON_DEBUG
            value: "true"

    graph:
      name: combiner
      type: COMBINER
      children:

      - name: model-a
        type: MODEL

      - name: model-b
        type: MODEL

    name: combiner-graph
    replicas: 1
    svcOrchSpec:
      env:
      - name: SELDON_LOG_LEVEL
        value: INFO
